const CACHE_KEY='formatech.drug-images.v2';
const memory=new Map();
function readCache(){try{return JSON.parse(localStorage.getItem(CACHE_KEY)||'{}')}catch{return{}}}
function writeCache(cache){try{localStorage.setItem(CACHE_KEY,JSON.stringify(cache))}catch{} }
function candidates(drug){return [...new Set([drug.trade_name,drug.commercial_name_ar,drug.arabic,drug.scientific_name,drug.active_ingredient,drug.active,drug.generic_name,drug.commercial_name_en].map(x=>String(x||'').trim()).filter(x=>x.length>2))]}
async function searchCommons(term,signal){const url=new URL('https://commons.wikimedia.org/w/api.php');url.search=new URLSearchParams({action:'query',generator:'search',gsrsearch:term,gsrnamespace:'6',gsrlimit:'3',prop:'imageinfo',iiprop:'url|mime',iiurlwidth:'420',format:'json',origin:'*'});const response=await fetch(url,{signal});if(!response.ok)return null;const pages=Object.values((await response.json()).query?.pages||{});const tokens=term.toLowerCase().split(/\s+/).filter(x=>x.length>3);const page=pages.find(x=>x.imageinfo?.[0]?.mime?.startsWith('image/')&&tokens.some(token=>String(x.title||'').toLowerCase().includes(token)));const info=page?.imageinfo?.[0];return info?.thumburl||info?.url?{url:info.thumburl||info.url,title:page.title,source:'Wikimedia Commons'}:null}
async function searchWiki(language,term,signal){const url=new URL(`https://${language}.wikipedia.org/w/api.php`);url.search=new URLSearchParams({action:'query',generator:'search',gsrsearch:term,gsrnamespace:'0',gsrlimit:'1',prop:'pageimages',piprop:'thumbnail',pithumbsize:'420',format:'json',origin:'*'});const response=await fetch(url,{signal});if(!response.ok)return null;const pages=Object.values((await response.json()).query?.pages||{});const tokens=term.toLowerCase().split(/\s+/).filter(x=>x.length>3);const page=pages.find(x=>tokens.some(token=>String(x.title||'').toLowerCase().includes(token)));return page?.thumbnail?.source?{url:page.thumbnail.source,title:page.title,language,source:'Wikipedia'}:null}
export async function getWikipediaImage(drug,signal){const key=String(drug.id||drug.barcode||drug.trade_name||drug.name||'').trim().toLowerCase();if(!key)return null;if(memory.has(key))return memory.get(key);const cache=readCache();if(cache[key]){memory.set(key,cache[key]);return cache[key]}
 for(const term of candidates(drug)){try{const common=await searchCommons(term,signal);if(common){memory.set(key,common);cache[key]=common;const keys=Object.keys(cache);if(keys.length>500)delete cache[keys[0]];writeCache(cache);return common}}catch(error){if(error.name==='AbortError')throw error}}
 for(const term of candidates(drug)){for(const language of ['ar','en']){try{const image=await searchWiki(language,term,signal);if(image){memory.set(key,image);cache[key]=image;const keys=Object.keys(cache);if(keys.length>500)delete cache[keys[0]];writeCache(cache);return image}}catch(error){if(error.name==='AbortError')throw error}}}
 return null
}
