import {useEffect,useMemo,useState} from 'react';
import {BookOpen,MessageCircle,Plus,Search,UserRound,WalletCards} from 'lucide-react';
import api from '../lib/ApiService';
import DeleteService from '../lib/DeleteService';
import DeleteButton from '../components/DeleteButton';

export default function Customers(){
 const [q,setQ]=useState(''),[customers,setCustomers]=useState([]),[error,setError]=useState(''),[show,setShow]=useState(false),[form,setForm]=useState({name:'',phone:'',address:''}),[payment,setPayment]=useState(null),[amount,setAmount]=useState(''),[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(null);
 const load=()=>api.listCustomers().then(d=>setCustomers(d.customers||d.items||[])).catch(e=>setError(e.message));
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>customers.filter(c=>`${c.name||c.full_name||''} ${c.phone||''}`.toLowerCase().includes(q.toLowerCase())),[customers,q]);
 async function add(e){e.preventDefault();setSaving(true);setError('');try{const d=await api.post('customers',form);setCustomers(x=>[d.customer,...x]);setForm({name:'',phone:'',address:''});setShow(false)}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function pay(e){e.preventDefault();if(!payment||Number(amount)<=0)return;setSaving(true);try{await api.post('customers',{id:payment.id,payment_amount:Number(amount),notes:'سداد من صفحة العملاء'});setCustomers(x=>x.map(c=>c.id===payment.id?{...c,credit_balance:Math.max(0,Number(c.credit_balance||0)-Number(amount))}:c));setPayment(null);setAmount('')}catch(e){setError(e.message)}finally{setSaving(false)}}
 async function remove(c){setDeleting(c.id);try{const r=await DeleteService.customer(c.id);setCustomers(x=>x.filter(item=>item.id!==c.id));if(r.offline)setError('تم الحذف محليًا وسيزامن عند عودة الإنترنت.')}catch(e){setError(e.message)}finally{setDeleting(null)}}
 function whatsapp(c){window.open(`https://wa.me/${(c.phone||'').replace(/\D/g,'')}?text=${encodeURIComponent(`مرحباً ${c.name||c.full_name}، رصيدكم المستحق ${c.credit_balance||0} ر.س.`)}`,'_blank')}
 return <main className="module-page"><div className="page-title"><div><div className="eyebrow"><UserRound size={15}/> إدارة العملاء والديون</div><h1>العملاء ودفتر الديون</h1><p>إضافة العملاء وتسجيل التحصيل وعرض الأرصدة من قاعدة البيانات.</p></div><button className="primary" onClick={()=>setShow(!show)}><Plus size={17}/> إضافة عميل</button></div>{error&&<div className="api-error">{error}</div>}<div className="module-stats"><Mini icon={UserRound} label="إجمالي العملاء" value={customers.length}/><Mini icon={WalletCards} label="إجمالي الديون" value={`${customers.reduce((a,c)=>a+Number(c.credit_balance||0),0).toFixed(2)} ر.س`} warn/><Mini icon={BookOpen} label="حسابات نشطة" value={customers.filter(c=>Number(c.credit_balance)>0).length}/></div>{show&&<form className="panel form-grid" onSubmit={add}><h2>إضافة عميل</h2><Field label="اسم العميل" value={form.name} onChange={v=>setForm({...form,name:v})} required/><Field label="الهاتف" value={form.phone} onChange={v=>setForm({...form,phone:v})}/><Field label="العنوان" value={form.address} onChange={v=>setForm({...form,address:v})}/><button className="primary form-submit" disabled={saving}>{saving?'جاري الحفظ...':'حفظ العميل'}</button></form>}{payment&&<form className="panel payment-form" onSubmit={pay}><h2>تسجيل سداد: {payment.name||payment.full_name}</h2><Field label="المبلغ" type="number" value={amount} onChange={setAmount} required/><button className="primary" disabled={saving}>تأكيد السداد</button><button type="button" className="soft-button" onClick={()=>setPayment(null)}>إلغاء</button></form>}<section className="panel"><div className="table-toolbar"><div><h2>دليل العملاء</h2><p>{filtered.length} عميل · مزامنة مباشرة</p></div><div className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن عميل"/></div></div>{filtered.length?<div className="data-table"><div className="table-row table-head"><span>العميل</span><span>الهاتف</span><span>الزيارات</span><span>الرصيد المستحق</span><span>إجراء</span></div>{filtered.map(c=><div className="table-row" key={c.id}><span className="person"><div className="person-avatar">{(c.name||c.full_name||'?')[0]}</div><b>{c.name||c.full_name}</b></span><span>{c.phone||'—'}</span><span>{c.visits||0}</span><span><strong className={Number(c.credit_balance)>0?'stock-low':''}>{Number(c.credit_balance||0).toFixed(2)} ر.س</strong></span><div className="row-actions"><button className="icon-button" title="تسجيل سداد" onClick={()=>setPayment(c)}><WalletCards size={16}/></button><button className="icon-button" title="إرسال واتساب" onClick={()=>whatsapp(c)}><MessageCircle size={16}/></button><DeleteButton compact disabled={deleting===c.id} confirmMessage={`سيتم حذف ${c.name||c.full_name||'هذا العميل'} مع دفتر ديونه. هل تريد المتابعة؟`} onDelete={()=>remove(c)}/></div></div>)}</div>:<div className="empty-state"><UserRound size={32}/><b>لا يوجد عملاء</b><span>أضف أول عميل لبدء دفتر الديون.</span></div>}</section></main>
}
function Field({label,value,onChange,type='text',required}){return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
function Mini({icon:Icon,label,value,warn}){return <div className="stat-card"><div className={`stat-icon ${warn?'warn':''}`}><Icon size={19}/></div><span>{label}</span><strong>{value}</strong></div>}
