import {useEffect,useMemo,useState} from 'react';
import {Barcode,BookOpen,ChevronLeft,ChevronRight,PackagePlus,Search} from 'lucide-react';
import {loadDrugLibrary,searchDrugLibrary} from '../lib/DrugLibrary';
import {useNavigate} from 'react-router-dom';
import DrugImageSearch from '../components/DrugImageSearch';
const PAGE_SIZE=60;
const field=(value)=>value===undefined||value===null||String(value).trim()===''?'غير مسجل':value;
export default function DrugLibrary(){
 const navigate=useNavigate();const [library,setLibrary]=useState([]),[q,setQ]=useState(''),[page,setPage]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{loadDrugLibrary().then(setLibrary).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);useEffect(()=>setPage(0),[q]);
 const results=useMemo(()=>q?searchDrugLibrary(library,q,Infinity):library,[library,q]);const totalPages=Math.max(1,Math.ceil(results.length/PAGE_SIZE));const visible=results.slice(page*PAGE_SIZE,(page+1)*PAGE_SIZE);
 function useDrug(drug){navigate('/inventory',{state:{drug,openForm:true}})}
 return <main className="module-page"><div className="page-title"><div><div className="eyebrow"><BookOpen size={15}/> المكتبة الدوائية</div><h1>مكتبة الأدوية المصرية</h1><p>بيانات مرجعية كاملة لكل صنف، ويمكن نقل أي صنف إلى المخزون.</p></div><button className="primary" onClick={()=>navigate('/inventory',{state:{openForm:true}})}><PackagePlus size={17}/> إضافة إلى المخزون</button></div>{error&&<div className="api-error">{error}</div>}<section className="panel drug-library-panel"><div className="table-toolbar"><div><h2>بيانات الأصناف</h2><p>{loading?'جاري تحميل المكتبة...':`${results.length.toLocaleString('ar-EG')} صنف`}</p></div><div className="library-search-actions"><div className="search-box library-search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="اسم تجاري أو علمي أو مادة فعالة"/></div><DrugImageSearch onText={text=>setQ(text)}/></div></div>{loading?<div className="empty-state">جاري تحميل جميع سجلات المكتبة...</div>:<><div className="drug-library-cards">{visible.map((d,i)=><article className="drug-library-card" key={`${d.trade_name}-${page}-${i}`}><header className="drug-library-card-head"><div><span className="drug-library-kicker">بيانات دوائية</span><h3>{field(d.trade_name)}</h3><p>{field(d.commercial_name_en)}</p></div><button className="text-button" onClick={()=>useDrug(d)}>استخدام في المخزون <Barcode size={13}/></button></header><div className="drug-details-grid"><Detail label="الاسم العلمي" value={d.scientific_name}/><Detail label="المادة الفعالة" value={d.active_ingredient}/><Detail label="الشركة المصنعة" value={d.manufacturer}/><Detail label="الشكل الدوائي" value={d.dosage_form}/><Detail label="التركيز" value={d.strength}/><Detail label="حجم العبوة" value={d.package_size}/><Detail label="التصنيف" value={d.drug_class}/><Detail label="طريق الاستخدام" value={d.route}/><Detail label="الباركود" value={d.barcode}/><Detail label="السعر المرجعي" value={d.library_price}/></div></article>)}</div><div className="library-pagination"><button className="outline-button" disabled={page===0} onClick={()=>setPage(x=>x-1)}><ChevronRight size={15}/> السابق</button><span>صفحة {page+1} / {totalPages}</span><button className="outline-button" disabled={page>=totalPages-1} onClick={()=>setPage(x=>x+1)}>التالي <ChevronLeft size={15}/></button></div></>}</section></main>
}
function Detail({label,value}){return <div className="drug-detail"><span>{label}</span><b>{field(value)}</b></div>}
