import {useEffect,useMemo,useState} from 'react';
import {ClipboardCheck,Package,RefreshCw,Save,Search,TriangleAlert} from 'lucide-react';
import api from '../lib/ApiService';

export default function InventoryAudit(){
 const [items,setItems]=useState([]),[counts,setCounts]=useState({}),[q,setQ]=useState(''),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function load(){setLoading(true);setError('');try{const data=await api.listMedicines();const next=data.items||[];setItems(next);setCounts(Object.fromEntries(next.map(item=>[item.id,String(item.stock_quantity??0)])));if(data.offline)setMessage('أنت في الوضع المحلي؛ ستتم المزامنة عند عودة الإنترنت.')}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const rows=useMemo(()=>items.filter(item=>JSON.stringify(item).toLowerCase().includes(q.toLowerCase())),[items,q]);
 const differences=items.map(item=>Number(counts[item.id]??item.stock_quantity)-Number(item.stock_quantity||0));
 const changed=items.filter(item=>Number(counts[item.id]??item.stock_quantity)!==Number(item.stock_quantity||0));
 const shortage=differences.filter(x=>x<0).reduce((sum,x)=>sum+Math.abs(x),0),surplus=differences.filter(x=>x>0).reduce((sum,x)=>sum+x,0);
 function setCount(id,value){setCounts(x=>({...x,[id]:value}));setMessage('');}
 async function save(){if(!changed.length){setMessage('لا توجد فروقات جديدة للحفظ.');return}setSaving(true);setError('');try{const results=await Promise.all(changed.map(item=>api.updateMedicine({id:item.id,stock_quantity:Number(counts[item.id]),selling_price:item.selling_price,cost_price:item.cost_price,expiry_date:item.expiry_date})));const updated=items.map(item=>{const result=results.find(x=>(x.item||{}).id===item.id);return result?.item||({...item,stock_quantity:Number(counts[item.id])})});setItems(updated);setCounts(Object.fromEntries(updated.map(item=>[item.id,String(item.stock_quantity??0)])));setMessage(`تم حفظ جرد ${changed.length} صنف وتحديث المخزون.${results.some(x=>x.offline)?' وسيتم رفع التعديلات عند عودة الإنترنت.':''}`)}catch(e){setError(e.message)}finally{setSaving(false)}}
 return <main className="module-page"><div className="page-title"><div><div className="eyebrow"><ClipboardCheck size={15}/> مراقبة المخزون</div><h1>جرد المخزون</h1><p>قارن الكمية المسجلة في المخزن بالكمية الفعلية ثم احفظ الفروقات.</p></div><div className="toolbar-actions"><button className="outline-button" onClick={load} disabled={loading}><RefreshCw size={15}/> تحديث</button><button className="primary" onClick={save} disabled={saving||!changed.length}><Save size={16}/> {saving?'جاري الحفظ...':'حفظ الجرد'}</button></div></div>{message&&<div className="library-status">{message}</div>}{error&&<div className="api-error">{error}</div>}<div className="module-stats"><Mini icon={Package} label="الأصناف" value={items.length}/><Mini icon={TriangleAlert} label="نقص في الجرد" value={shortage} warn/><Mini icon={ClipboardCheck} label="زيادة في الجرد" value={surplus}/></div><section className="panel"><div className="table-toolbar"><div><h2>كشف الجرد</h2><p>{changed.length} صنف بانتظار الحفظ</p></div><div className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث بالاسم أو الباركود"/></div></div>{loading?<div className="empty-state">جاري تحميل المخزون...</div>:rows.length?<div className="data-table audit-table"><div className="table-row table-head"><span>الدواء</span><span>الباركود</span><span>الكمية الدفترية</span><span>الكمية الفعلية</span><span>الفرق</span></div>{rows.map(item=>{const book=Number(item.stock_quantity||0),actual=Number(counts[item.id]??book),diff=actual-book;return <div className={`table-row ${diff!==0?'audit-changed':''}`} key={item.id}><span><b>{item.trade_name}</b><small>{item.scientific_name||item.active_ingredient||'—'}</small></span><span>{item.barcode||'—'}</span><span>{book}</span><span><input className="audit-count" type="number" min="0" value={counts[item.id]??book} onChange={e=>setCount(item.id,e.target.value)} aria-label={`الكمية الفعلية لـ ${item.trade_name}`}/></span><span className={diff<0?'stock-low':diff>0?'stock-up':''}>{diff>0?`+${diff}`:diff}</span></div>})}</div>:<div className="empty-state"><ClipboardCheck size={32}/><b>لا توجد أصناف مطابقة</b><span>غيّر كلمة البحث أو أضف أدوية إلى المخزون.</span></div>}</section></main>
}
function Mini({icon:Icon,label,value,warn}){return <div className="stat-card"><div className={`stat-icon ${warn?'warn':''}`}><Icon size={19}/></div><span>{label}</span><strong>{value}</strong></div>}
