import {useEffect,useMemo,useRef,useState} from 'react';
import {useLocation} from 'react-router-dom';
import {AlertTriangle,Barcode,Boxes,CalendarDays,PackagePlus,Search} from 'lucide-react';
import api from '../lib/ApiService';
import DeleteService from '../lib/DeleteService';
import DeleteButton from '../components/DeleteButton';
import BarcodeScannerButton from '../components/BarcodeScannerButton';
import DrugImage from '../components/DrugImage';
import {exportDrugLibrary,findDrugByBarcode,loadDrugLibrary,mergeBarcodeMappings,searchDrugLibrary} from '../lib/DrugLibrary';

const emptyForm={trade_name:'',scientific_name:'',active_ingredient:'',barcode:'',manufacturer:'',dosage_form:'',strength:'',package_size:'',stock_quantity:0,selling_price:0,expiry_date:''};
export default function Inventory(){
 const location=useLocation();
 const [items,setItems]=useState([]);const [query,setQuery]=useState('');const barcodeFileRef=useRef(null);const imageFileRef=useRef(null);const [bulkStatus,setBulkStatus]=useState('');const [showForm,setShowForm]=useState(false);const [error,setError]=useState('');const [deleting,setDeleting]=useState(null);const [library,setLibrary]=useState([]);const [libraryError,setLibraryError]=useState('');const [form,setForm]=useState(emptyForm);
 useEffect(()=>{api.listMedicines().then(d=>setItems(d.items||[])).catch(e=>setError(e.message));loadDrugLibrary().then(setLibrary).catch(e=>setLibraryError(e.message))},[]);
 const filtered=useMemo(()=>items.filter(x=>JSON.stringify(x).toLowerCase().includes(query.toLowerCase())),[items,query]);
 const suggestions=useMemo(()=>searchDrugLibrary(library,form.trade_name),[library,form.trade_name]);
 async function importBarcodes(file){if(!file)return;setBulkStatus('جاري قراءة ملف الباركود...');try{const raw=await file.text();const data=file.name.toLowerCase().endsWith('.json')?JSON.parse(raw):parseCsv(raw);const result=mergeBarcodeMappings(library,data);setLibrary(result.items);setBulkStatus(`تمت مطابقة ${result.matched} من ${result.total} سجل. تم حفظ الأكواد على هذا الجهاز.`)}catch(e){setBulkStatus(`تعذر استيراد الملف: ${e.message||'صيغة غير صحيحة'}`)}finally{if(barcodeFileRef.current)barcodeFileRef.current.value=''}}
 function applyDrug(drug){setForm(x=>({...x,trade_name:drug.trade_name||x.trade_name,scientific_name:drug.scientific_name||x.scientific_name,active_ingredient:drug.active_ingredient||x.active_ingredient,barcode:drug.barcode||x.barcode,manufacturer:drug.manufacturer||x.manufacturer,dosage_form:drug.dosage_form||x.dosage_form,strength:drug.strength||x.strength,package_size:drug.package_size||x.package_size,selling_price:drug.library_price??x.selling_price}));setError('تم جلب تفاصيل الدواء من المكتبة. أدخل الكمية والصلاحية وراجع السعر قبل الحفظ.');}
 useEffect(()=>{if(location.state?.openForm){setShowForm(true);if(location.state.drug)applyDrug(location.state.drug)}},[location.state]);
 function onBarcode(code){const value=String(code||'').trim();const drug=findDrugByBarcode(library,value);if(drug){applyDrug(drug);setError(`تم العثور على ${drug.trade_name||'الدواء'} في المكتبة وتم تعبئة التفاصيل.`)}else{setForm(x=>({...x,barcode:value}));setError(`الباركود ${value} غير موجود في المكتبة. أضف التفاصيل يدويًا ثم احفظه.`)}}
 function update(name,value){setForm(x=>({...x,[name]:value}));if(name==='barcode'&&value.trim())onBarcode(value)}
 function chooseImage(file){if(!file)return;if(!file.type.startsWith('image/')){setError('اختر ملف صورة صالحًا.');return}if(file.size>2*1024*1024){setError('حجم الصورة يجب ألا يتجاوز 2 ميجابايت.');return}const reader=new FileReader();reader.onload=()=>setForm(x=>({...x,image_data:reader.result}));reader.readAsDataURL(file)}
 async function add(e){e.preventDefault();setError('');const next={...form,stock_quantity:Number(form.stock_quantity),selling_price:Number(form.selling_price),min_stock_alert:5};try{const d=await api.createMedicine(next);setItems(x=>[d.item||next,...x]);setForm(emptyForm);setShowForm(false)}catch(e){setError(e.message)}}
 async function remove(id){setDeleting(id);setError('');try{const result=await DeleteService.medicine(id);setItems(x=>x.filter(m=>m.id!==id));if(result.offline)setError('تم حذف الدواء من الجهاز وسيتم حذفه من السحابة عند عودة الإنترنت.')}catch(e){setError(e.message)}finally{setDeleting(null)}}
 return <main className="module-page"><PageHead eyebrow="إدارة المخزون" title="المخزون والأدوية" desc="أضف الدواء بالباركود ليتم جلب تفاصيله من المكتبة المحلية." action={<div className="inventory-head-actions"><button className="outline-button" onClick={()=>barcodeFileRef.current?.click()}>استيراد أكواد جماعيًا</button><button className="primary" onClick={()=>setShowForm(!showForm)}><PackagePlus size={17}/> إضافة دواء</button><input ref={barcodeFileRef} hidden type="file" accept=".csv,.json,text/csv,application/json" onChange={e=>importBarcodes(e.target.files?.[0])}/></div>}/>{error&&<div className="api-error">{error}</div>}{bulkStatus&&<div className="library-status">{bulkStatus} <button className="text-button" onClick={()=>exportDrugLibrary(library)}>تصدير المكتبة المحدثة</button> <a className="text-button" href="/barcode-import-template.csv" download>تحميل قالب CSV</a></div>}{libraryError&&<div className="api-error">تعذر تحميل مكتبة الأدوية: {libraryError}</div>}<div className="module-stats"><Mini icon={Boxes} label="إجمالي الأصناف" value={items.length||'—'}/><Mini icon={AlertTriangle} label="تحت الحد الأدنى" value={items.filter(x=>x.stock_quantity<=x.min_stock_alert).length||0} warn/><Mini icon={CalendarDays} label="صلاحية قريبة" value={items.filter(x=>x.expiry_date&&new Date(x.expiry_date)<new Date(Date.now()+90*86400000)).length||0} warn/></div>
 {showForm&&<form className="panel form-grid inventory-add-form" onSubmit={add}><h2>إضافة دواء من المكتبة أو بالباركود</h2><div className="barcode-entry"><Field label="الباركود" value={form.barcode} onChange={v=>update('barcode',v)}/><BarcodeScannerButton onCode={onBarcode} onError={setError}/></div><Field label="الاسم التجاري" value={form.trade_name} onChange={v=>update('trade_name',v)} required/><Field label="الاسم العلمي" value={form.scientific_name} onChange={v=>update('scientific_name',v)}/><Field label="المادة الفعالة" value={form.active_ingredient} onChange={v=>update('active_ingredient',v)}/><Field label="الشركة المصنعة" value={form.manufacturer} onChange={v=>update('manufacturer',v)}/><Field label="الشكل الدوائي" value={form.dosage_form} onChange={v=>update('dosage_form',v)}/><Field label="التركيز" value={form.strength} onChange={v=>update('strength',v)}/><Field label="حجم العبوة" value={form.package_size} onChange={v=>update('package_size',v)}/><Field label="الكمية" type="number" value={form.stock_quantity} onChange={v=>update('stock_quantity',v)}/><Field label="سعر البيع" type="number" value={form.selling_price} onChange={v=>update('selling_price',v)}/><Field label="تاريخ الصلاحية" type="date" value={form.expiry_date} onChange={v=>update('expiry_date',v)}/><div className="image-upload-field"><span>صورة المنتج <small>(اختياري)</small></span><button type="button" className="outline-button" onClick={()=>imageFileRef.current?.click()}>اختيار صورة من الجهاز</button><input ref={imageFileRef} hidden type="file" accept="image/*" onChange={e=>chooseImage(e.target.files?.[0])}/>{form.image_data&&<img src={form.image_data} alt="معاينة المنتج"/>}</div>{suggestions.length>0&&<div className="drug-suggestions"><small>نتائج المكتبة — اختر صنفًا لتعبئة التفاصيل:</small>{suggestions.map(drug=><button type="button" key={`${drug.barcode}-${drug.trade_name}`} onClick={()=>applyDrug(drug)}><b>{drug.trade_name}</b><span>{drug.active_ingredient||drug.scientific_name||'تفاصيل دوائية'} {drug.barcode&&` · ${drug.barcode}`}</span></button>)}</div>}<button className="primary form-submit">حفظ الدواء في المخزن</button></form>}
 <section className="panel"><div className="table-toolbar"><div><h2>قائمة الأدوية</h2><p>{filtered.length} صنف مسجل</p></div><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالاسم أو المادة أو الباركود"/><Barcode size={16}/></div></div><div className="data-table"><div className="table-row table-head"><span>الدواء</span><span>المادة الفعالة</span><span>المخزون</span><span>السعر</span><span>الصلاحية</span><span/></div>{filtered.map(m=><div className="table-row" key={m.id}><span className="drug-cell"><DrugImage drug={m}/><span><b>{m.trade_name}</b><small>{m.scientific_name||'غير مسجل'}{m.barcode&&` · ${m.barcode}`}</small></span></span><span>{m.active_ingredient||'—'}</span><span><strong className={m.stock_quantity<=m.min_stock_alert?'stock-low':''}>{m.stock_quantity}</strong><small> / حد {m.min_stock_alert||5}</small></span><span>{m.selling_price} ر.س</span><span>{m.expiry_date||'—'}</span><DeleteButton compact disabled={deleting===m.id} confirmMessage={`سيتم حذف ${m.trade_name||'هذا الدواء'} من الجهاز والسحابة. هل تريد المتابعة؟`} onDelete={()=>remove(m.id)}/></div>)}</div></section></main>
}
function PageHead({eyebrow,title,desc,action}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Mini({icon:Icon,label,value,warn}){return <div className="stat-card"><div className={`stat-icon ${warn?'warn':''}`}><Icon size={19}/></div><span>{label}</span><strong>{value}</strong></div>}
function parseCsv(text){const lines=text.replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const cells=line=>(line.match(/"(?:[^"]|"")*"|[^,]+/g)||[]).map(x=>x.trim().replace(/^"|"$/g,'').replace(/""/g,'"'));const headers=cells(lines[0]).map(x=>x.toLowerCase());return lines.slice(1).map(line=>{const values=cells(line);return Object.fromEntries(headers.map((header,i)=>[header,values[i]||'']))}).filter(row=>row.barcode)}
function Field({label,value,onChange,type='text',required}){return <label className="field"><span>{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required}/></label>}
