import {useEffect,useRef,useState} from 'react';
import {Download,Eye,FileText,LoaderCircle,Printer,Receipt,Search} from 'lucide-react';
import {useNavigate,useParams} from 'react-router-dom';
import api from '../lib/ApiService';
import {saveAndExportPDF} from '../lib/pdfExport';

const localInvoices=()=>{try{return JSON.parse(localStorage.getItem('formatech.invoices')||'[]')}catch{return[]}};

export default function Invoices(){
  const {number}=useParams();const navigate=useNavigate();const [invoices,setInvoices]=useState(localInvoices);const [query,setQuery]=useState('');
  const selected=number?invoices.find(x=>x.invoice_number===decodeURIComponent(number)):null;
  useEffect(()=>{api.listSales().then(d=>{if(d.sales?.length)setInvoices(x=>merge(d.sales,x))}).catch(()=>{})},[]);
  if(selected)return <InvoiceView invoice={selected} onBack={()=>navigate('/invoices')}/>;
  const filtered=invoices.filter(x=>`${x.invoice_number} ${x.payment_type}`.toLowerCase().includes(query.toLowerCase()));
  return <main className="module-page invoices-page"><div className="page-title"><div><div className="eyebrow"><Receipt size={15}/> إدارة الفواتير</div><h1>الفواتير والمبيعات</h1><p>عرض واضح لكل فاتورة مع خيار التحميل والمشاركة بصيغة PDF.</p></div><button className="primary" onClick={()=>navigate('/pos')}><Receipt size={17}/> فاتورة جديدة</button></div><section className="panel"><div className="table-toolbar"><div><h2>سجل الفواتير</h2><p>{filtered.length} فاتورة</p></div><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث برقم الفاتورة"/></div></div>{filtered.length?<div className="data-table"><div className="table-row invoice-row table-head"><span>رقم الفاتورة</span><span>التاريخ</span><span>الدفع</span><span>الإجمالي</span><span>الحالة</span><span/></div>{filtered.map(x=><div className="table-row invoice-row" key={x.invoice_number}><span><b>{x.invoice_number}</b><small>{x.items?.length||0} أصناف</small></span><span>{formatDate(x.created_at)}</span><span>{paymentLabel(x.payment_type)}</span><span><strong>{money(x.total_amount)} ر.س</strong></span><span><em className="invoice-status">مكتملة</em></span><button className="icon-button" title="عرض الفاتورة" onClick={()=>navigate(`/invoices/${encodeURIComponent(x.invoice_number)}`)}><Eye size={16}/></button></div>)}</div>:<div className="empty-state invoice-empty"><FileText size={34}/><b>لا توجد فواتير بعد</b><span>أنشئ فاتورة من نقطة البيع وستظهر هنا.</span></div>}</section></main>
}

export function InvoiceView({invoice,onBack}){
  const paperRef=useRef(null);const [exporting,setExporting]=useState(false);const [exportError,setExportError]=useState('');
  async function exportInvoice(){setExportError('');setExporting(true);try{await saveAndExportPDF(paperRef.current,`فاتورة-${invoice.invoice_number}`,{margin:6,html2canvas:{scale:2},jsPDF:{format:'a4',orientation:'portrait'}})}catch(error){setExportError(error?.message||'تعذر إنشاء أو مشاركة ملف PDF.')}finally{setExporting(false)}}
  return <main className="module-page invoice-view"><div className="invoice-actions no-print"><button className="soft-button" onClick={onBack}>← العودة للفواتير</button><div className="invoice-action-group"><button className="soft-button" onClick={()=>window.print()}><Printer size={16}/> طباعة</button><button className="primary" onClick={exportInvoice} disabled={exporting}>{exporting?<LoaderCircle className="spin" size={16}/>:<Download size={16}/>} {exporting?'جاري تجهيز PDF...':'تحميل ومشاركة PDF'}</button></div></div>{exportError&&<div className="api-error no-print">{exportError}</div>}<section ref={paperRef} className="invoice-paper"><header className="invoice-brand"><div><div className="brand-mark">ف</div><h1>فرما تيك</h1><p>نظام إدارة الصيدلية</p></div><div className="invoice-heading"><span>فاتورة بيع</span><strong>{invoice.invoice_number}</strong><small>{formatDate(invoice.created_at,true)}</small></div></header><div className="invoice-meta"><div><span>طريقة الدفع</span><b>{paymentLabel(invoice.payment_type)}</b></div><div><span>عدد الأصناف</span><b>{invoice.items?.length||0}</b></div><div><span>حالة الفاتورة</span><b className="invoice-status">مكتملة</b></div></div><table className="invoice-lines"><thead><tr><th>الصنف</th><th>الكمية</th><th>سعر الوحدة</th><th>الإجمالي</th></tr></thead><tbody>{(invoice.items||[]).map((x,i)=><tr key={x.medicine_id||i}><td>{x.name||x.trade_name||'دواء صيدلي'}</td><td>{x.quantity}</td><td>{money(x.unit_price)} ر.س</td><td>{money(Number(x.unit_price)*Number(x.quantity))} ر.س</td></tr>)}</tbody></table><div className="invoice-total"><span>الإجمالي النهائي</span><strong>{money(invoice.total_amount)} ر.س</strong></div><footer>شكراً لتعاملكم مع فرما تيك — يرجى الاحتفاظ بالفاتورة</footer></section></main>
}
function merge(a,b){const map=new Map([...a,...b].map(x=>[x.invoice_number,x]));return [...map.values()].sort((x,y)=>new Date(y.created_at||0)-new Date(x.created_at||0))}function money(v){return Number(v||0).toFixed(2)}function formatDate(v,full=false){return v?new Date(v).toLocaleString('ar-SA',{dateStyle:'medium',...(full?{timeStyle:'short'}:{})}):'الآن'}function paymentLabel(v){return ({cash:'نقدي',card:'بطاقة',credit:'آجل'})[v]||v||'نقدي'}
