import {useEffect,useRef,useState} from 'react';
import {Download,Eye,FileText,LoaderCircle,Printer,Receipt,Search} from 'lucide-react';
import api from '../lib/ApiService';
import {saveAndExportPDF} from '../lib/pdfExport';

export default function PurchaseInvoices(){
 const [purchases,setPurchases]=useState([]),[query,setQuery]=useState(''),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{api.listPurchases().then(d=>setPurchases(d.purchases||[])).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);
 const filtered=purchases.filter(x=>`${x.id||''} ${x.supplier_name||''} ${x.company_name||''}`.toLowerCase().includes(query.toLowerCase()));
 if(selected)return <PurchaseInvoiceView purchase={selected} onBack={()=>setSelected(null)}/>;
 return <main className="module-page"><div className="page-title"><div><div className="eyebrow"><Receipt size={15}/> المشتريات والمخازن</div><h1>فواتير الشراء</h1><p>فواتير طلبيات المخزن المسجلة مع الموردين وتكاليف الاستلام.</p></div></div>{error&&<div className="api-error">{error}</div>}<section className="panel"><div className="table-toolbar"><div><h2>سجل فواتير الشراء</h2><p>{loading?'جاري تحميل الفواتير...':`${filtered.length} فاتورة شراء`}</p></div><div className="search-box"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ابحث بالمورد أو رقم الطلبية"/></div></div>{loading?<div className="empty-state">جاري تحميل أوامر الشراء...</div>:filtered.length?<div className="data-table purchase-invoices-table"><div className="table-row table-head"><span>رقم الطلبية</span><span>المورد</span><span>عدد الأصناف</span><span>الإجمالي</span><span>الحالة</span><span/></div>{filtered.map(p=><div className="table-row" key={p.id}><span><b>PO-{String(p.id).slice(0,8)}</b><small>{formatDate(p.created_at)}</small></span><span>{p.supplier_name||'بدون مورد'}<small>{p.company_name||''}</small></span><span>{p.items?.length||p.item_count||0}</span><span><strong>{money(p.total_cost)} ر.س</strong></span><span><em className="invoice-status">{p.status==='received'?'تم الاستلام':p.status||'مسودة'}</em></span><button className="icon-button" title="عرض فاتورة الشراء" onClick={()=>setSelected(p)}><Eye size={16}/></button></div>)}</div>:<div className="empty-state"><FileText size={34}/><b>لا توجد فواتير شراء</b><span>أنشئ طلبية من صفحة الموردين وسيتم إصدار فاتورتها هنا.</span></div>}</section></main>
}

function PurchaseInvoiceView({purchase,onBack}){const paperRef=useRef(null);const [exporting,setExporting]=useState(false);const items=purchase.items||[];const total=Number(purchase.total_cost||items.reduce((a,x)=>a+Number(x.quantity||0)*Number(x.cost_price||0),0));async function exportInvoice(){setExporting(true);try{await saveAndExportPDF(paperRef.current,`فاتورة-شراء-${String(purchase.id).slice(0,8)}`,{margin:6,html2canvas:{scale:2},jsPDF:{format:'a4',orientation:'portrait'}})}finally{setExporting(false)}}return <main className="module-page invoice-view"><div className="invoice-actions no-print"><button className="soft-button" onClick={onBack}>← العودة لفواتير الشراء</button><div className="invoice-action-group"><button className="soft-button" onClick={()=>window.print()}><Printer size={16}/> طباعة</button><button className="primary" onClick={exportInvoice} disabled={exporting}>{exporting?<LoaderCircle className="spin" size={16}/>:<Download size={16}/>} {exporting?'جاري تجهيز PDF...':'تحميل ومشاركة PDF'}</button></div></div><section ref={paperRef} className="invoice-paper"><header className="invoice-brand"><div><div className="brand-mark">ف</div><h1>فرما تيك</h1><p>نظام إدارة الصيدلية</p></div><div className="invoice-heading"><span>فاتورة شراء</span><strong>PO-{String(purchase.id).slice(0,8)}</strong><small>{formatDate(purchase.created_at,true)}</small></div></header><div className="invoice-meta"><div><span>المورد</span><b>{purchase.supplier_name||'بدون مورد'}</b></div><div><span>الشركة</span><b>{purchase.company_name||'—'}</b></div><div><span>الحالة</span><b className="invoice-status">{purchase.status==='received'?'تم الاستلام':purchase.status||'مسودة'}</b></div></div><table className="invoice-lines"><thead><tr><th>الصنف</th><th>الكمية</th><th>سعر التكلفة</th><th>الإجمالي</th></tr></thead><tbody>{items.map((x,i)=><tr key={x.medicine_id||i}><td>{x.name||'دواء'}</td><td>{x.quantity}</td><td>{money(x.cost_price)} ر.س</td><td>{money(Number(x.quantity)*Number(x.cost_price))} ر.س</td></tr>)}</tbody></table><div className="invoice-total"><span>إجمالي فاتورة الشراء</span><strong>{money(total)} ر.س</strong></div><footer>تم استلام الطلبية وإضافتها إلى مخزون فرما تيك</footer></section></main>}
function money(v){return Number(v||0).toFixed(2)}function formatDate(v,full=false){return v?new Date(v).toLocaleString('ar-SA',{dateStyle:'medium',...(full?{timeStyle:'short'}:{})}):'الآن'}
