name: Scheduled Drug List Update

on:
  schedule:
    # يعمل تلقائياً في منتصف الليل يوم 1 من كل 3 شهور (كل 90 يوماً)
    - cron: '0 0 1 */3 *'
  workflow_dispatch: # يتيح لك زر التشغيل اليدوي من جيت هب متى شئت

jobs:
  update-repo-drugs:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest drug database JSON
        run: |
          echo "جاري سحب أحدث ملف أدوية..."
          curl -L "https://raw.githubusercontent.com/karem505/egyptian-drug-database/main/data/egyptian-drugs.json" -o public/egyptian-drugs.json
          echo "تم التحديث بنجاح في مجلد public!"

      - name: Commit and push changes if file updated
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: automatically update egyptian-drugs.json [skip ci]"
          branch: main
          file_pattern: 'public/egyptian-drugs.json'
